# Generated by Django 5.0.5 on 2024-05-07 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=180)),
                ('tipe', models.CharField(max_length=180)),
                ('modl', models.CharField(max_length=180)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('autom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_api.automobile')),
            ],
        ),
        migrations.CreateModel(
            name='PartFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='todo_api.parts')),
            ],
        ),
    ]
